production:
  delivery_method: smtp

development:
  delivery_method: smtp

test:
  delivery_method: test

delivery:
  default_sender_name: Brett Cassette - Snack Pack
  default_sender_address: brett@snackpack.delivery
  default_sender_reply_to: no-reply@snackpack.delivery
  default_locale: 'en-US'
  store_period_in_months: 2
  s3_bucket: 'snackpack'

development_smtp: &development_smtp
  address: localhost
  domain: localhost
  authentication: plain
  port: 1025

sendgrid_smtp_settings:
  sendgrid_defaults: &sendgrid_defaults
    address: smtp.sendgrid.net
    domain: snackpack.delivery
    authentication: plain
    port: 587
  production:
    <<: *sendgrid_defaults
  development:
    <<: *development_smtp
  test:
    <<: *sendgrid_defaults

mailgun_smtp_settings:
  mailgun_defaults: &mailgun_defaults
    address: smtp.mailgun.org
    domain: snacks.snackpackmailer.com
    authentication: plain
    port: 587
  production:
    <<: *mailgun_defaults
  development:
    <<: *development_smtp
  test:
    <<: *mailgun_defaults

template:
  renderable_providers:
    - sendgrid
    - mailgun
