default: &default
  adapter: mysql2
  encoding: utf8
  pool: 15
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: snackpack_development

test:
  <<: *default
  database: snackpack_test

production:
  <<: *default
  database: snackpack_production
  username: snackpack
  pool: 25
  password: <%= ENV['SNACKPACK_DATABASE_PASSWORD'] %>
